baseURL = "mbwong.github.io"
relativeURLs = true
title = "Michael Wong"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]
publishDir = "docs"

[params]
    shortbio = "PhD Student, MIT"
    logo = "mw.png" 
    
