relativeURLs = true
title = "Michael B. Wong"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]
publishDir = "docs"

[params]
    shortbio = "Assistant professor<br>HKU Business School"
    logo = "mw.png" 
    
